### ISSUE TITLE
[1.8.2] iPhone 5S / 8.4.1 - Create - User can create lomotif without video (picture)

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#214]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button
3. Switch to Motif tab on Albums screen
4. Select any motif
5. Tap Apply button and hold it on Albums screen
6. Uncheck the selected motif when Apply button is held
7. Release the Apply button -> Find Music screen appears
8. Tap Apply button on Find Music screen
9. Tap OK button on dialog

Expected result: User can't create lomotif without video or picture

Actual result: Lomotif without video (picture) was created

Next Action:
10. Try to play created lomotif

Expected result: User sees error message that lomotif doesn't include video

Actual result: Nothing happened

Next Action:
11. Tap export button on Create screen
12. Tap YES button on dialog

Expected result: User sees sharing screen

Actual result: The application doesn't respond

Video: [Recording.zip](https://github.com/Lomotif/lomotif-ios-issues/files/171021/Recording.zip)

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomtotif-ios@96a9cfa82974e7fc803b5e541328ddb55d78aa98

**Comment by vysohanych** [comment]
@tsukisa @xiuie I can still reproduce this issue in 1.7.12 version. Should I create a separate bug for new version?
