### ISSUE TITLE
[1.8.4] iPhone 6 / 9.3.1 - App crash - Motif search multiple times with random keywords

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#271]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on start
3. Tap on Motif tab from Album screen
4. Click on search bar
5. Enter keyword "aaa"
6. It will display few motifs as results
7. Now click on Back button (<) available left to search bar
8. Now, again enter random keyword in search bar (I have entered entered "Aaaghgh") and search for that
9. It will not give any result
10. Again click on Back button (<) available left to search bar

Expected result: When click on Back button, it should redirect to previous Motif screen

Actual result: Application crash

![img_1595](https://cloud.githubusercontent.com/assets/9691390/14519339/d1019e82-023b-11e6-90a2-300edb681675.PNG)

![img_1596](https://cloud.githubusercontent.com/assets/9691390/14519341/d10a6b5c-023b-11e6-8f0f-0f4a23939ebd.PNG)

![img_1597](https://cloud.githubusercontent.com/assets/9691390/14519340/d1081686-023b-11e6-831e-d417705dc547.PNG)

![img_1598](https://cloud.githubusercontent.com/assets/9691390/14519338/d0fd4ec2-023b-11e6-92f1-3a59f0645413.PNG)

**Comment by Dipamit** [comment]
I am able to reproduce this issue on iPhone 5/8.3 with Lomotif [1.8.4]

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@9cd1919fa738c18609ef65b061011a1d9794e005

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can still reproduce this issue for build [1.8.5] on iPhone 6 / iOS 9.3.1 every time

Please find crash log.

[Crash log for #271](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UYWprOGlxZER1Zjg)
