### ISSUE TITLE
[1.8.5] iPad 2 / iOS 9.3.1 - Create - Second's pointer is shifted when user sets min or max value

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#275]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Open one of exists lomotif
3. Expand the Adjust section
4. Set pointer to 3 secs or 30 secs
5. Tap home button on Create screen and confirm the changes
6. Open the same lomotif again
7. Expand the Adjust section

Expected result: User sees second's pointer in correct position

Actual result: Second's pointer is shifted

Video: [Recording #120.zip](https://github.com/Lomotif/lomotif-ios-issues/files/222135/Recording.120.zip)

![2016-04-16_1325](https://cloud.githubusercontent.com/assets/3593359/14580480/edb27e10-03d6-11e6-960f-dbf0beace8b1.png)

![2016-04-16_1326](https://cloud.githubusercontent.com/assets/3593359/14580482/f4d39cec-03d6-11e6-9eab-e5f9f12a2cbd.png)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.8.5] on iPhone 6 / iOS 9.3.1

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@f7b65996cd5c6998d8217bf663997a8abdc68f99

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can still reproduce this issue for build [1.8.6] on iPhone 6 / iOS 9.3.1

And there is a overlapping of pointer with showing 30 sec time.

![img_1683](https://cloud.githubusercontent.com/assets/9691390/14584901/d607a77c-047b-11e6-9cb9-e96f2b7c14d6.PNG)
